name: first
on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: stepone
        uses: actions/cache@v2.1.3
      - name: steptwo
        run: env | sort
  job2:
    name: second job
    runs-on: windows-latest
    steps: 
      - name: stepone
        uses: actions/cache@v2.1.3
      - name: steptwo
        run: "Get-ChildItem Env: | Sort-Object Name"