name: first
<<<<<<< HEAD

on: pull_request

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: "Get-ChildItem Env: | Sort-Object Name"
=======
on: pull_request

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - stepone:
        uses: actions/cache@v2.1.3
      - steptwo:
        run: env | sort
  job2:
    name: second job
    runs-on: windows-latest
    steps: 
      - stepone:
        uses: actions/cache@v2.1.3
      - steptwo: 
        run: "Get-ChildItem Env: | Sort-Object Name"
>>>>>>> origin/main
