name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup Python environment
      uses: actions/setup-python@v2
    - name: Install requirements
      run: pip install --quiet --requirement ./Ch04/04_02/requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 ./Ch04/04_02/*.py
        pylint --disable=C0301 --disable=C0326 ./Ch04/04_02/*.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast